services:
  flask_no_db:
    build:
      context: ./flask_no_db
    ports:
      - "5001:5000"
    networks:
      - app_network

  flask_with_db:
    build:
      context: ./flask_with_db
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - "5002:5000" 
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - flask_no_db
      - flask_with_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
