services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db



flask_with-Dockerfile:
  build: .
  container_name: simple-flask-app:latest
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  depends_on:
    - mongodb
  environment:
    MONGO_URI=mongodb://mongodb:27017/

volumes:
  mongodb_data: