apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: qnempont
spec:
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80 # Port exposé par le service
      targetPort: 5000 # Port du conteneur
  type: ClusterIP
