apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: qnempont
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: dylanlartiste/mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"

