apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: qnempont
spec:
  replicas: 1 # Nombre de pods
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
        - name: simple-flask-app
          image: dylanlartiste/simple_flask_app-flask_no_db:latest # Image Docker
          ports:
            - containerPort: 5000 # Port exposé par le conteneur
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: "100m" # 1/10 CPU
              memory: "100Mi" # 100 Mo
            limits:
              cpu: "200m" # 1/5 CPU
              memory: "200Mi" # 200 Mo
