apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: qnempont
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: dylanlartiste/mongo:latest
        ports:
        - containerPort: 27017
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10 #10 secondes pour laisser le conteneur démarrer
          periodSeconds: 10 #10 secondes entre chaque vérification
          timeoutSeconds: 1 #1 seconde pour chaque vérification
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"

